sudo: required
language: node_js
services:
  - docker
before_install:
  - docker build -t peelmicro/docker-react -f Dockerfile.dev .
script:
  - docker run peelmicro/docker-react npm run test -- --coverage
